### ISSUE TITLE
Final Deliverable Checklist v1.0 for week 19

### ISSUE THREAD

**Issue by rhysprice2** [rhysprice2/GamesSystem#8]
- [x] Instance Testing for clsSales, clsSalesLine
- [x] Instance Testing for all properties 
- [x] Check Code with PT4 On TDD to make sure these tests are up to date 
- [x] Creating the Find Method for Both clsSales and clsSalesLine
- [x] Update Class Diagram to reflect changes from order to sales

--GitHub Backup -- 
- [ ] Master has been backed up on Sunday

**Comment by Skylark5678** [comment]
- [ ] Instance Testing for clsGames
- [ ] Instance Testing for all Properties
- [ ] Boundary Tests for GameTitle, GameDev, GamePublisher
- [ ] Boundary Tests For GameStock (Integer Tests)

**Comment by rhysprice2** [comment]
As of 15/02/2019 15:07PM this thread is closed
